#
# ████████╗███╗   ███╗██╗   ██╗██╗  ██╗
# ╚══██╔══╝████╗ ████║██║   ██║╚██╗██╔╝
#    ██║   ██╔████╔██║██║   ██║ ╚███╔╝
#    ██║   ██║╚██╔╝██║██║   ██║ ██╔██╗
#    ██║   ██║ ╚═╝ ██║╚██████╔╝██╔╝ ██╗
#    ╚═╝   ╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═╝
#
# Terminal multiplexer
# https://github.com/tmux/tmux

# Environment variables
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins/'

# Set prefix key
# unbind C-b
set -g prefix C-Space
set -g prefix2 'C-\'
bind C-Space send-prefix

# Reload config
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "~/.config/tmux/tmux.conf reloaded"

# Pane Controls
bind h split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind-key x kill-pane # Killing without confirmation

# Window navigations
bind-key -r < swap-window -t - 
bind-key -r > swap-window -t +
bind -n M-h previous-window # Shift Alt vim keys to switch windows
bind -n M-l next-window
bind -n S-Left  previous-window # Shift arrow to switch windows
bind -n S-Right next-window

# General
set -g default-terminal tmux-256color
set -ga terminal-overrides ",tmux-256color:Tc"
set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Status bar
set -g status-position top
bind-key b set-option status 
# set -g status-justify left # Center status bar items

# Theme customizations
set -g @catppuccin_flavour 'mocha'
set -g @tokyo-night-tmux_window_id_style digital
set -g @tokyo-night-tmux_pane_id_style hsquare
set -g @tokyo-night-tmux_zoom_id_style dsquare
set -g @tokyo-night-tmux_show_datetime 0
set -g @tokyo-night-tmux_date_format MYD
set -g @tokyo-night-tmux_time_format 12H
set -g @tokyo-night-tmux_show_path 0
set -g @tokyo-night-tmux_path_format relative
set -g @tokyo-night-tmux_window_id_style dsquare
set -g @tokyo-night-tmux_window_id_style dsquare
set -g @tokyo-night-tmux_show_git 1
set -g @tokyo-night-tmux_theme moon    # storm | day | default to 'night'
set -g @tokyo-night-tmux_transparent 1  # 1 or 0
set -g @minimal-tmux-use-arrow true
set -g @minimal-tmux-right-arrow ""
set -g @minimal-tmux-left-arrow ""
# set -g @oasis_flavor "lagoon_dark"  # Optional: defaults to lagoon_dark

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'fcsonline/tmux-thumbs'
# set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin "janoamaral/tokyo-night-tmux"
# set -g @plugin 'uhs-robert/tmux-oasis'
set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'niksingh710/minimal-tmux-status'

# Vi mode for copy
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection # -- tmux-yank custom Keybindings
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle # -- tmux-yank custom Keybindings
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel # -- tmux-yank custom Keybindings

# Paste copied string with tmux-thumbs
set -g @thumbs-command 'echo -n {} | pbcopy'

run-shell ~/.tmux/plugins/tmux-thumbs/tmux-thumbs.tmux

run '~/.tmux/plugins/tpm/tpm'
