general.import = ["~/.config/omarchy/current/theme/alacritty.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10.5

[font.bold]
family = "Maple Mono NF"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NF"
style = "Bold Italic"

[font.italic]
family = "Maple Mono NF"
style = "Italic"

[font.normal]
family = "Maple Mono NF"
style = "Light"

[font.offset]
x = 0
y = 1

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[terminal]
osc52 = "CopyPaste"

[scrolling]
history = 10000

[window]
dynamic_padding = false
opacity = 0.80
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0
